name: My-Pipeline

on:
  workflow_dispatch:
  push:
   branches:
      - 'master'
jobs:

  build_and_Deploy:

    runs-on: test-vm
    steps:
    - uses: actions/checkout@v2    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Check Existing Java Version
      run: java -version
